# Checking whether model is property trained.

## Set up

In [1]:
import os
import json
import glob
import scipy
import numpy as np

import pandas as pd
import glob

import warnings
warnings.filterwarnings('ignore')

In [2]:
BASE_MODEL_PATH="trained_model"

In [3]:
from models.modelutils import dir2filedict_sorted, split_fdict
import random

Using TensorFlow backend.


Load category information and all of image paths.

In [4]:
trdict = dir2filedict_sorted("data_fgvc/train")
valdict = dir2filedict_sorted("data_fgvc/valid")
categories = [str(i) for i in range(0, 100)]

In [5]:
valdict['0'][0:5]

['data_fgvc/valid/0/0062781.jpg',
 'data_fgvc/valid/0/0113201.jpg',
 'data_fgvc/valid/0/0450014.jpg',
 'data_fgvc/valid/0/0602177.jpg',
 'data_fgvc/valid/0/0716386.jpg']

Here is expected outputs.   
All the outputs in {*train.ipynb*, *classifier_similarity.ipynb*, *train_multiclass_classifier.ipynb*, *train_second.ipynb*} must be the same. 

['data_fgvc/valid/0/0062781.jpg',  
 'data_fgvc/valid/0/0198101.jpg',  
 'data_fgvc/valid/0/0536721.jpg',  
 'data_fgvc/valid/0/0602177.jpg',  
 'data_fgvc/valid/0/0817494.jpg']

In [6]:
# target is validation set.
fdict = valdict

## Compute $ClassSim$ using OVR classifiers

Now compute our proposed similarities using trained OVR classifiers in *train.ipynb*.

In [7]:
from models.modelutils import load_best_model_if_exist
import os
from models.processor import DataSet

In [18]:
#0, 7, 25
model_0 = load_best_model_if_exist("trained_model/modelfgcv_0")

In [12]:
ds = DataSet()

In [26]:
test_files = valdict['0']+valdict['7']+valdict['25']

In [27]:
len(test_files)

21

In [28]:
[len(valdict[str(cat)]) for cat in range(0, 5)]

[7, 7, 7, 7, 7]

In [29]:
datas = ds.files_to_dataset(test_files)

In [30]:
res = model_0.predict(datas)

In [31]:
res[:, 1]

array([  8.92395899e-02,   2.59536813e-04,   5.92470281e-02,
         3.28918062e-02,   1.39725283e-01,   5.34679629e-02,
         1.82478607e-01,   1.58299913e-03,   2.88571522e-04,
         1.88934747e-02,   4.61065769e-03,   1.49370171e-03,
         6.01889798e-04,   4.31226520e-03,   3.46300541e-03,
         1.46281039e-02,   1.24871347e-03,   5.20068670e-06,
         8.64843838e-04,   9.01830941e-03,   6.41005952e-03], dtype=float32)

In [32]:
model_7 = load_best_model_if_exist("trained_model/modelfgcv_7")

In [33]:
res7 = model_7.predict(datas)

In [34]:
res7[:, 1]

array([ 0.79513288,  0.94284797,  0.52979416,  0.004935  ,  0.977696  ,
        0.91841048,  0.95773572,  0.99248064,  0.97794801,  0.98844063,
        0.99942929,  0.99754745,  0.9922483 ,  0.98539889,  0.71566725,
        0.95446295,  0.98618662,  0.99400312,  0.98530722,  0.97016662,
        0.97104281], dtype=float32)

In [35]:
model_25 = load_best_model_if_exist("trained_model/modelfgcv_25")

In [36]:
res25 = model_25.predict(datas)

In [37]:
res25[:, 1]

array([ 0.96423489,  0.95057374,  0.98104322,  0.98065484,  0.98563081,
        0.96160883,  0.92907143,  0.99927717,  0.9276554 ,  0.95660198,
        0.90638232,  0.95786446,  0.93434954,  0.94946223,  0.99442321,
        0.94495463,  0.89362717,  0.98713171,  0.88144904,  0.97600114,
        0.97630274], dtype=float32)