# Checking whether model is property trained.

## Set up

In [1]:
import os
import json
import glob
import scipy
import numpy as np

import pandas as pd
import glob

import warnings
warnings.filterwarnings('ignore')

In [2]:
BASE_MODEL_PATH="trained_model"

In [3]:
from models.modelutils import dir2filedict_sorted, split_fdict
import random

Using TensorFlow backend.


Load category information and all of image paths.

In [4]:
trdict = dir2filedict_sorted("data_fgvc/train")
valdict = dir2filedict_sorted("data_fgvc/valid")
categories = [str(i) for i in range(0, 100)]

In [5]:
valdict['0'][0:5]

['data_fgvc/valid/0/0062781.jpg',
 'data_fgvc/valid/0/0113201.jpg',
 'data_fgvc/valid/0/0450014.jpg',
 'data_fgvc/valid/0/0602177.jpg',
 'data_fgvc/valid/0/0716386.jpg']

Here is expected outputs.   
All the outputs in {*train.ipynb*, *classifier_similarity.ipynb*, *train_multiclass_classifier.ipynb*, *train_second.ipynb*} must be the same. 

['data_fgvc/valid/0/0062781.jpg',  
 'data_fgvc/valid/0/0198101.jpg',  
 'data_fgvc/valid/0/0536721.jpg',  
 'data_fgvc/valid/0/0602177.jpg',  
 'data_fgvc/valid/0/0817494.jpg']

In [6]:
from models.modelutils import load_best_model_if_exist
import os
from models.processor import DataSet

In [7]:
ds = DataSet()

In [8]:
test_files = valdict['0']+valdict['7']+valdict['25']+valdict['62']

In [9]:
len(test_files)

28

In [10]:
[len(valdict[str(cat)]) for cat in [0, 7, 25, 62]]

[7, 7, 7, 7]

In [11]:
datas = ds.files_to_dataset(test_files)

In [12]:
#0, 7, 25, 62
model_0 = load_best_model_if_exist("trained_model/modelfgcv_0")

In [13]:
res = model_0.predict(datas)

In [23]:
res[:, 1]

array([  9.94502664e-01,   9.99776185e-01,   9.46093053e-02,
         9.93320346e-01,   9.85995948e-01,   8.57002742e-04,
         2.20971178e-05,   8.95473957e-02,   1.03166234e-03,
         3.42383100e-05,   1.10675371e-03,   9.99631011e-05,
         1.30190374e-02,   9.84561622e-01,   1.49690479e-01,
         3.36077320e-03,   2.46371469e-03,   1.92337666e-07,
         6.13217521e-03,   3.51649214e-05], dtype=float32)

In [15]:
train_files = trdict['0'][0:5]+trdict['7'][0:5]+trdict['25'][0:5]+trdict['62'][0:5]

In [16]:
train_datas = ds.files_to_dataset(train_files)

In [17]:
res = model_0.predict(train_datas)

In [18]:
res[:, 1]

array([  9.94502664e-01,   9.99776185e-01,   9.46093053e-02,
         9.93320346e-01,   9.85995948e-01,   8.57002742e-04,
         2.20971178e-05,   8.95473957e-02,   1.03166234e-03,
         3.42383100e-05,   1.10675371e-03,   9.99631011e-05,
         1.30190374e-02,   9.84561622e-01,   1.49690479e-01,
         3.36077320e-03,   2.46371469e-03,   1.92337666e-07,
         6.13217521e-03,   3.51649214e-05], dtype=float32)

In [28]:
zero_only = ds.files_to_dataset(trdict['0'])

In [29]:
res = model_0.predict(zero_only)

In [32]:
sum(res[:, 1] > 0.5)

9

In [32]:
model_7 = load_best_model_if_exist("trained_model/modelfgcv_7")

In [33]:
res7 = model_7.predict(datas)

In [34]:
res7[:, 1]

array([ 0.79513288,  0.94284797,  0.52979416,  0.004935  ,  0.977696  ,
        0.91841048,  0.95773572,  0.99248064,  0.97794801,  0.98844063,
        0.99942929,  0.99754745,  0.9922483 ,  0.98539889,  0.71566725,
        0.95446295,  0.98618662,  0.99400312,  0.98530722,  0.97016662,
        0.97104281], dtype=float32)

In [14]:
model_25 = load_best_model_if_exist("trained_model/modelfgcv_25")

In [15]:
res25 = model_25.predict(datas)

In [19]:
res25[:, 1][14:]

array([ 0.99834442,  0.99435568,  0.99043137,  0.99914241,  0.99164093,
        0.9886502 ,  0.9931531 ], dtype=float32)

In [17]:
model_62 = load_best_model_if_exist("trained_model/modelfgcv_62")

In [18]:
res62 = model_62.predict(datas)

In [19]:
res62[:, 1]

array([  2.70922808e-03,   3.45351337e-03,   4.39824886e-04,
         4.29836586e-02,   1.73179619e-02,   5.35412168e-04,
         2.34004995e-03,   2.12970865e-03,   1.04577988e-02,
         5.24299592e-03,   1.39063880e-01,   2.19665449e-02,
         1.49431609e-04,   1.12679023e-04,   2.94336583e-04,
         6.06759787e-02,   1.71862741e-03,   8.16847105e-03,
         2.24659638e-03,   1.50426361e-03,   4.61724028e-03,
         9.97252524e-01,   9.99970675e-01,   6.08387887e-01,
         9.99990582e-01,   9.99999762e-01,   9.99977827e-01,
         1.00000000e+00], dtype=float32)